version: 2
jobs:
  build_ubuntu_18.04:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            apt update
            apt install sudo
      - run:
          name: install
          command: . install.sh
  build_ubuntu_16.04:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            apt update
            apt install sudo
      - run:
          name: install
          command: . install.sh
workflows:
  version: 2
  build:
    jobs:
      - build_ubuntu_18.04
      - build_ubuntu_16.04
