version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            apt update
            apt install sudo
      - run:
          name: install
          command: . install.sh
workflows:
  version: 2
  build:
    jobs:
      - build
