version: 2
  build_debian_9:
    docker:
      - image: debian:9
    steps:
      - run:
          name: install required tools for circle-ci
          command: |
            apt update
            apt install -y sudo git openssh-client wget curl ca-certificates gnupg
      - checkout
      - run:
          name: install
          command: . install.sh
jobs:
  build_ubuntu_18.04:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: install required tools for circle-ci
          command: |
            apt update
            apt install -y sudo git openssh-client wget curl ca-certificates gnupg
      - checkout
      - run:
          name: install
          command: . install.sh
  build_ubuntu_16.04:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: install required tools for circle-ci
          command: |
            apt update
            apt install -y sudo git openssh-client wget curl ca-certificates gnupg
      - checkout
      - run:
          name: install
          command: . install.sh
workflows:
  version: 2
  build:
    jobs:
      - build_ubuntu_18.04
      - build_ubuntu_16.04
      - build_debian_9
